# Generated by Django 5.2.6 on 2025-09-28 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(max_length=255, unique=True, verbose_name='Instance ID')),
                ('instance_name', models.CharField(max_length=255, verbose_name='Instance Name')),
                ('ownerPhone', models.CharField(max_length=255, verbose_name='Owner Phone')),
                ('profileName', models.CharField(max_length=255, verbose_name='Profile Name')),
                ('connection_status', models.CharField(max_length=255, verbose_name='Connection Status')),
                ('instance_api_key', models.CharField(max_length=255, verbose_name='Instance API Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connection',
                'verbose_name_plural': 'Connections',
            },
        ),
    ]
