# Generated by Django 5.2.6 on 2025-09-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='connection_status',
            field=models.CharField(choices=[('open', 'Open'), ('connecting', 'Connecting'), ('disconnected', 'Disconnected')], max_length=255, verbose_name='Connection Status'),
        ),
    ]
