# Generated by Django 5.2.6 on 2025-10-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_alter_connection_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='connection_attempts',
            field=models.IntegerField(default=0, help_text='Total connection attempts', verbose_name='Connection Attempts'),
        ),
        migrations.AddField(
            model_name='connection',
            name='connection_phase',
            field=models.CharField(choices=[('initial', 'Initial'), ('waiting', 'Waiting for Connection'), ('retrying', 'Retrying'), ('connected', 'Connected'), ('failed', 'Failed'), ('help_needed', 'Help Needed')], default='initial', help_text='Current phase of the connection process', max_length=20, verbose_name='Connection Phase'),
        ),
        migrations.AddField(
            model_name='connection',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, help_text='Last retry attempt timestamp', null=True, verbose_name='Last Retry At'),
        ),
        migrations.AddField(
            model_name='connection',
            name='max_retries_reached',
            field=models.BooleanField(default=False, help_text='Whether max retries have been reached', verbose_name='Max Retries Reached'),
        ),
        migrations.AddField(
            model_name='connection',
            name='retry_count',
            field=models.IntegerField(default=0, help_text='Number of retry attempts', verbose_name='Retry Count'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_status',
            field=models.CharField(choices=[('open', 'Open'), ('connecting', 'Connecting'), ('close', 'Disconnected')], max_length=255, verbose_name='Connection Status'),
        ),
    ]
