# Generated by Django 5.2.6 on 2025-10-01 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_connection_connection_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='last_qr_request_at',
            field=models.DateTimeField(blank=True, help_text='Last QR code request timestamp', null=True, verbose_name='Last QR Request At'),
        ),
        migrations.AddField(
            model_name='connection',
            name='max_qr_requests_reached',
            field=models.BooleanField(default=False, help_text='Whether max QR code requests have been reached', verbose_name='Max QR Requests Reached'),
        ),
        migrations.AddField(
            model_name='connection',
            name='qr_code_requests',
            field=models.IntegerField(default=0, help_text='Number of QR code requests', verbose_name='QR Code Requests'),
        ),
    ]
