# Generated by Django 5.2.7 on 2025-10-26 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0004_connection_last_qr_request_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_connection_per_user'),
        ),
    ]
