# Generated by Django 5.2.6 on 2025-10-01 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +1234567890)', max_length=20, null=True),
        ),
    ]
