# Generated by Django 5.2.7 on 2025-10-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When verification email was sent', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Email verification token', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='newsletter_subscribed',
            field=models.BooleanField(default=False, help_text='Newsletter subscription status'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether user completed welcome onboarding'),
        ),
    ]
