# Generated by Django 5.2.7 on 2025-10-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_unique_email_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp_attempts',
            field=models.IntegerField(default=0, help_text='Number of OTP verification attempts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_code',
            field=models.CharField(blank=True, help_text='OTP code for WhatsApp verification', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='When OTP was generated', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='WhatsApp verification status'),
        ),
    ]
