# Generated by Django 5.2.7 on 2025-10-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_otp_attempts_userprofile_otp_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_sent_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verification_token',
        ),
    ]
