# Generated by Django 5.2.7 on 2025-10-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_userprofile_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +1234567890)', max_length=20, null=True, unique=True),
        ),
    ]
