# Generated by Django 5.2.7 on 2025-10-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
    ]
