# Generated by Django 5.2.7 on 2025-10-26 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_userprofile_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_attempts',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp_created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='timezone',
        ),
    ]
