# Generated by Django 5.2.7 on 2025-10-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_userprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('profile', 'Personal Profile'), ('business', 'Business Profile'), ('verify', 'WhatsApp Verification'), ('complete', 'Completed')], default='welcome', help_text='Current step in the onboarding process', max_length=20),
        ),
    ]
