# Generated by Django 5.2.7 on 2025-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_userprofile_onboarding_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('business', 'Business Profile'), ('verify', 'WhatsApp Verification'), ('complete', 'Completed')], default='welcome', help_text='Current step in the onboarding process', max_length=20),
        ),
    ]
