# Generated by Django 5.2.7 on 2025-10-03 18:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='WozapAutoAgent', max_length=255, unique=True)),
                ('description', models.TextField(default='WozapAutoAgent is a smart AI agent that will help you answer your WhatsApp queries.')),
                ('system_prompt', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_locked', models.BooleanField(default=False)),
                ('is_locked_until', models.DateTimeField(blank=True, null=True)),
                ('locked_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('instance', models.CharField(max_length=255)),
                ('remote_jid', models.CharField(max_length=255)),
                ('from_me', models.BooleanField()),
                ('push_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('conversation', models.CharField(max_length=255)),
                ('message_type', models.CharField(max_length=255)),
                ('instance_id', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('sender', models.CharField(max_length=255)),
                ('quoted_message', models.JSONField()),
                ('is_group', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
