# Generated by Django 5.2.7 on 2025-10-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdata',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webhookdata',
            name='response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
