# Generated by Django 5.2.7 on 2025-10-04 12:14

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0002_webhookdata_is_processed_webhookdata_response_text'),
    ]

    operations = [
        # Enable pgvector extension first
        VectorExtension(),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='webhookdata',
            options={'ordering': ['-date_time'], 'verbose_name': 'Webhook Data', 'verbose_name_plural': 'Webhook Data'},
        ),
    ]
