# Generated by Django 5.2.7 on 2025-10-04 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0004_agent_user_alter_agent_is_locked_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['-created_at'], 'verbose_name': 'Knowledge Base Entry', 'verbose_name_plural': 'Knowledge Base Entries'},
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='chunk_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='file_type',
            field=models.CharField(default='pdf', max_length=50),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='parent_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
