# Generated by Django 5.2.7 on 2025-10-10 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0005_alter_knowledgebase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('LINK', 'Explicit Link'), ('SIMILAR', 'Vector Similarity'), ('REFERENCE', 'Content Reference'), ('TAG', 'Shared Tag')], max_length=20)),
                ('strength', models.FloatField(default=1.0)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='aiengine.knowledgebase')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='aiengine.knowledgebase')),
            ],
            options={
                'verbose_name': 'Document Relationship',
                'verbose_name_plural': 'Document Relationships',
                'unique_together': {('source', 'target', 'relationship_type')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='aiengine.knowledgebase')),
            ],
            options={
                'verbose_name': 'Document Tag',
                'verbose_name_plural': 'Document Tags',
                'unique_together': {('knowledge_base', 'name')},
            },
        ),
    ]
