# Generated by Django 5.2.7 on 2025-10-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0006_documentrelationship_documenttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(default='WozapAutoAgent', max_length=255),
        ),
    ]
