# Generated by Django 5.2.7 on 2025-10-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0007_alter_agent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdata',
            name='last_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookdata',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='webhookdata',
            name='processing_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookdata',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
