# Generated by Django 5.2.7 on 2025-10-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0008_webhookdata_last_processed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdata',
            name='context_injection',
            field=models.TextField(blank=True, help_text='Additional context to inject into the agent prompt during reprocessing', null=True),
        ),
    ]
