# Generated by Django 5.2.7 on 2025-10-14 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0009_webhookdata_context_injection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webhookdata',
            name='context_injection',
        ),
        migrations.RemoveField(
            model_name='webhookdata',
            name='last_processed_at',
        ),
        migrations.RemoveField(
            model_name='webhookdata',
            name='last_updated_at',
        ),
        migrations.RemoveField(
            model_name='webhookdata',
            name='processing_attempts',
        ),
        migrations.RemoveField(
            model_name='webhookdata',
            name='processing_error',
        ),
    ]
