# Generated by Django 5.2.7 on 2025-10-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0010_remove_webhookdata_context_injection_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documenttag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='knowledge_bases', to='aiengine.documenttag'),
        ),
        migrations.RemoveField(
            model_name='documenttag',
            name='knowledge_base',
        ),
    ]
