# Generated by Django 5.2.7 on 2025-10-14 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0011_alter_documenttag_unique_together_knowledgebase_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledgebase',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='knowledgebase',
            name='user',
        ),
        migrations.DeleteModel(
            name='DocumentRelationship',
        ),
        migrations.DeleteModel(
            name='DocumentTag',
        ),
        migrations.DeleteModel(
            name='KnowledgeBase',
        ),
    ]
