# Generated by Django 5.2.7 on 2025-10-16 17:19

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0015_conversationthread_conversationcheckpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationmessage',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
