# Generated by Django 5.2.7 on 2025-10-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0016_update_embedding_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationmessage',
            name='input_tokens',
            field=models.IntegerField(blank=True, help_text='Number of input tokens used', null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='model_name',
            field=models.CharField(blank=True, help_text='Model used for this message', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='output_tokens',
            field=models.IntegerField(blank=True, help_text='Number of output tokens generated', null=True),
        ),
        migrations.AddField(
            model_name='conversationmessage',
            name='total_tokens',
            field=models.IntegerField(blank=True, help_text='Total tokens used (input + output)', null=True),
        ),
    ]
