# Generated by Django 5.2.7 on 2025-10-19 17:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0017_add_token_tracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='webhookdata',
            name='message_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='webhookdata',
            index=models.Index(fields=['message_id'], name='aiengine_we_message_c785d7_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdata',
            index=models.Index(fields=['is_processed'], name='aiengine_we_is_proc_d60269_idx'),
        ),
    ]
