# Generated by Django 5.2.7 on 2025-10-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0018_alter_webhookdata_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdata',
            name='needs_reply',
            field=models.BooleanField(default=True),
        ),
    ]
