# Generated by Django 5.2.7 on 2025-10-26 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0019_webhookdata_needs_reply'),
        ('business', '0003_alter_businessprofile_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent', to='business.businessprofile'),
        ),
    ]
