# Generated by Django 5.2.8 on 2025-11-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0022_remove_conversationmessage_image_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookdata',
            name='base64_file',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookdata',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
