# Generated by Django 5.2.7 on 2025-10-17 18:38

import django.db.models.deletion
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='knowledge_base/%Y/%m/')),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(default='pdf', max_length=50)),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.IntegerField(default=0)),
                ('parent_document_id', models.CharField(db_index=True, max_length=255)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Base Entry',
                'verbose_name_plural': 'Knowledge Base Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'parent_document_id'], name='knowledgeba_user_id_5167df_idx'), models.Index(fields=['parent_document_id', 'chunk_index'], name='knowledgeba_parent__b71ab1_idx')],
            },
        ),
    ]
