# Generated by Django 5.2.6 on 2025-10-01 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('password_change', 'Password Change Confirmation'), ('connection_success', 'WhatsApp Connection Success'), ('system', 'System Notification'), ('other', 'Other')], help_text='Type of email sent', max_length=20)),
                ('recipient_email', models.EmailField(help_text='Email address of the recipient', max_length=254)),
                ('subject', models.CharField(help_text='Email subject line', max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent Successfully'), ('failed', 'Failed to Send'), ('pending', 'Pending')], default='pending', help_text='Current status of the email', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the email was successfully sent', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When the email failed to send', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if email failed to send')),
                ('template_used', models.CharField(blank=True, help_text='Email template used', max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Context data used in email template')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request that triggered the email', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the request that triggered the email')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the email log was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the email log was last updated')),
                ('recipient_user', models.ForeignKey(blank=True, help_text='User who received the email (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_type'], name='audit_email_email_t_dcc18b_idx'), models.Index(fields=['recipient_email'], name='audit_email_recipie_f3aeee_idx'), models.Index(fields=['status'], name='audit_email_status_f92ca5_idx'), models.Index(fields=['created_at'], name='audit_email_created_ce79dd_idx'), models.Index(fields=['recipient_user'], name='audit_email_recipie_4f4674_idx')],
            },
        ),
    ]
