# Generated by Django 5.2.7 on 2025-10-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('password_change', 'Password Change Confirmation'), ('connection_success', 'WhatsApp Connection Success'), ('email_verification', 'Email Verification'), ('system', 'System Notification'), ('other', 'Other')], help_text='Type of email sent', max_length=20),
        ),
    ]
