# Generated by Django 5.2.7 on 2025-10-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_emaillog_email_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='connection_used',
            field=models.CharField(blank=True, help_text='WhatsApp connection instance used to send message', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='message_type',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', help_text='Type of message (email or whatsapp)', max_length=10),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='recipient_phone',
            field=models.CharField(blank=True, help_text='Phone number of the recipient (for WhatsApp messages)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('welcome', 'Welcome Email'), ('password_reset', 'Password Reset'), ('password_change', 'Password Change Confirmation'), ('connection_success', 'WhatsApp Connection Success'), ('email_verification', 'Email Verification'), ('otp_verification', 'OTP Verification'), ('system', 'System Notification'), ('other', 'Other')], help_text='Type of message sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='recipient_email',
            field=models.EmailField(blank=True, help_text='Email address of the recipient (for email messages)', max_length=254, null=True),
        ),
    ]
