# Generated by Django 5.2.7 on 2025-10-10 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_emaillog_connection_used_emaillog_message_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('welcome', 'Welcome Message'), ('password_reset', 'Password Reset'), ('password_change', 'Password Change Confirmation'), ('connection_success', 'WhatsApp Connection Success'), ('otp_verification', 'OTP Verification'), ('system', 'System Notification'), ('other', 'Other')], help_text='Type of notification sent', max_length=20)),
                ('recipient_phone', models.CharField(blank=True, help_text='Phone number of the recipient', max_length=20, null=True)),
                ('connection_used', models.CharField(blank=True, help_text='WhatsApp connection instance used to send message', max_length=255, null=True)),
                ('subject', models.CharField(help_text='Message subject line', max_length=255)),
                ('status', models.CharField(choices=[('sent', 'Sent Successfully'), ('failed', 'Failed to Send'), ('pending', 'Pending')], default='pending', help_text='Current status of the notification', max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the notification was successfully sent', null=True)),
                ('failed_at', models.DateTimeField(blank=True, help_text='When the notification failed to send', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if notification failed to send')),
                ('template_used', models.CharField(blank=True, help_text='Message template used', max_length=100)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Context data used in message template')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request that triggered the notification', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the request that triggered the notification')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the notification log was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the notification log was last updated')),
                ('recipient_user', models.ForeignKey(blank=True, help_text='User who received the notification (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='EmailLog',
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['notification_type'], name='audit_notif_notific_2ca1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient_phone'], name='audit_notif_recipie_1914e6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['status'], name='audit_notif_status_0a1470_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['created_at'], name='audit_notif_created_56911e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['recipient_user'], name='audit_notif_recipie_307025_idx'),
        ),
    ]
