# Generated by Django 5.2.7 on 2025-10-17 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiengine', '0017_add_token_tracking'),
        ('audit', '0004_notificationlog_delete_emaillog_and_more'),
        ('connections', '0004_connection_last_qr_request_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, help_text='Conversation thread ID', max_length=255)),
                ('remote_jid', models.CharField(help_text='WhatsApp contact/group ID', max_length=255)),
                ('message_type', models.CharField(choices=[('human', 'Human Message'), ('ai', 'AI Response'), ('system', 'System Message')], max_length=10)),
                ('input_tokens', models.IntegerField(blank=True, help_text='Number of input tokens used', null=True)),
                ('output_tokens', models.IntegerField(blank=True, help_text='Number of output tokens generated', null=True)),
                ('total_tokens', models.IntegerField(blank=True, help_text='Total tokens used (input + output)', null=True)),
                ('model_name', models.CharField(blank=True, help_text='Model used for this message', max_length=100, null=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('conversation_turn', models.IntegerField(default=1, help_text='Turn number in conversation')),
                ('search_performed', models.BooleanField(default=False, help_text='Whether knowledge base search was performed')),
                ('knowledge_base_used', models.BooleanField(default=False, help_text='Whether knowledge base was used in response')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aiengine.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Conversation Log',
                'verbose_name_plural': 'AI Conversation Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_aicon_user_id_cd74fd_idx'), models.Index(fields=['thread_id', 'created_at'], name='audit_aicon_thread__daaaee_idx'), models.Index(fields=['message_type'], name='audit_aicon_message_89115a_idx'), models.Index(fields=['created_at'], name='audit_aicon_created_b7645f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConnectionActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'Connection Created'), ('connected', 'Connection Established'), ('disconnected', 'Connection Lost'), ('qr_requested', 'QR Code Requested'), ('retry_attempted', 'Retry Attempted'), ('status_changed', 'Status Changed'), ('deleted', 'Connection Deleted')], max_length=20)),
                ('connection_status', models.CharField(blank=True, max_length=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional event metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='connections.connection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Connection Activity Log',
                'verbose_name_plural': 'Connection Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_conne_user_id_f7e5aa_idx'), models.Index(fields=['connection', 'created_at'], name='audit_conne_connect_3dc57e_idx'), models.Index(fields=['event_type'], name='audit_conne_event_t_732477_idx'), models.Index(fields=['created_at'], name='audit_conne_created_5a1fe9_idx')],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(blank=True, help_text='Document identifier', max_length=255, null=True)),
                ('action', models.CharField(choices=[('upload', 'Document Uploaded'), ('delete', 'Document Deleted'), ('search', 'Knowledge Base Search'), ('chunk_created', 'Document Chunked'), ('embedding_created', 'Embedding Generated')], max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('chunks_count', models.IntegerField(blank=True, help_text='Number of chunks created', null=True)),
                ('search_query', models.TextField(blank=True, help_text='Search query used', null=True)),
                ('results_count', models.IntegerField(blank=True, help_text='Number of results returned', null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Base Activity Log',
                'verbose_name_plural': 'Knowledge Base Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_knowl_user_id_de789d_idx'), models.Index(fields=['action'], name='audit_knowl_action_374a12_idx'), models.Index(fields=['document_id'], name='audit_knowl_documen_941a84_idx'), models.Index(fields=['created_at'], name='audit_knowl_created_c39490_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('profile_update', 'Profile Updated'), ('password_change', 'Password Changed'), ('email_verification', 'Email Verified'), ('whatsapp_verification', 'WhatsApp Verified'), ('onboarding_completed', 'Onboarding Completed'), ('api_access', 'API Access'), ('other', 'Other')], max_length=25)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_usera_user_id_b3442a_idx'), models.Index(fields=['action'], name='audit_usera_action_4ce53a_idx'), models.Index(fields=['created_at'], name='audit_usera_created_3381d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='WebhookActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance', models.CharField(help_text='WhatsApp instance ID', max_length=255)),
                ('event_type', models.CharField(choices=[('message', 'Message Received'), ('status', 'Status Update'), ('connection', 'Connection Event'), ('error', 'Error Event'), ('other', 'Other')], max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_jid', models.CharField(help_text='WhatsApp contact/group ID', max_length=255)),
                ('is_group', models.BooleanField(default=False)),
                ('processing_time_ms', models.IntegerField(blank=True, help_text='Processing time in milliseconds', null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('response_sent', models.BooleanField(default=False, help_text='Whether a response was sent')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional webhook metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Webhook Activity Log',
                'verbose_name_plural': 'Webhook Activity Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_webho_user_id_a5f60f_idx'), models.Index(fields=['instance', 'created_at'], name='audit_webho_instanc_8c87f0_idx'), models.Index(fields=['event_type'], name='audit_webho_event_t_60d78f_idx'), models.Index(fields=['created_at'], name='audit_webho_created_051911_idx')],
            },
        ),
    ]
