# Generated by Django 5.2.7 on 2025-10-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_businessprofile_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class (e.g., bi-tag, bi-box)', max_length=50, null=True),
        ),
    ]
