# Generated by Django 5.2.7 on 2025-10-26 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='WhatsApp phone verification status'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='otp_attempts',
            field=models.IntegerField(default=0, help_text='Number of OTP verification attempts'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='otp_code',
            field=models.CharField(blank=True, help_text='OTP code for WhatsApp verification', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, help_text='When OTP was generated', null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='phone_number',
            field=models.CharField(default='+25471234567', help_text='Business WhatsApp number for OTP verification', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Customer phone number', max_length=20, null=True),
        ),
    ]
