# Generated by Django 5.2.7 on 2025-10-27 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_cart_phone_number_businessprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time of appointment', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='buffer_minutes',
            field=models.PositiveIntegerField(default=15, help_text='Buffer time in minutes between appointments'),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='appointment_slot',
            field=models.ForeignKey(blank=True, help_text='Optional appointment slot (deprecated with dynamic scheduling)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='business.appointmentslot'),
        ),
    ]
