# Generated by Django 5.2.7 on 2025-10-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_add_dynamic_appointment_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='phone',
        ),
    ]
