name: Django checks

on: [push, pull_request]

jobs:
  django-check:
    name: Run Django system checks
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install system deps (psycopg2, etc.)
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev python3-dev build-essential

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare environment
        run: |
          mkdir -p logs staticfiles media
        shell: bash

      - name: Run Django system checks
        env:
          # Minimal env for checks; uses sqlite by default in base/settings.py
          SECRET_KEY: dummy-secret-key
          DEBUG: 'False'
          DATABASE_ENGINE: 'sqlite'
        run: |
          python manage.py check


